-- Private cloud mirror for the Flashcard Reminder System.
-- Apply once in a new Supabase project's SQL Editor.

create table if not exists public.cards (
  id text primary key,
  deck text not null,
  type text not null check (type in ('qa', 'term', 'cloze')),
  front text not null,
  back text not null,
  source_file text not null,
  source_line integer not null,
  ease double precision not null default 2.5,
  interval_days integer not null default 0,
  repetitions integer not null default 0,
  due_date date not null,
  created_date date not null,
  last_reviewed date,
  suspended boolean not null default false,
  orphaned boolean not null default false
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  card_id text not null references public.cards(id),
  reviewed_at date not null,
  grade integer not null check (grade between 1 and 4),
  interval_before integer not null,
  interval_after integer not null,
  ease_before double precision not null,
  ease_after double precision not null
);

create table if not exists public.reminders_sent (
  date date primary key,
  due_total integer not null,
  status text not null
);

create table if not exists public.note_files (
  source_file text primary key,
  content_hash text not null
);

create index if not exists cards_due_idx on public.cards(due_date);
create index if not exists reviews_card_idx on public.reviews(card_id);
create index if not exists reviews_date_idx on public.reviews(reviewed_at);

alter table public.cards enable row level security;
alter table public.reviews enable row level security;
alter table public.reminders_sent enable row level security;
alter table public.note_files enable row level security;

revoke all on public.cards from anon, authenticated;
revoke all on public.reviews from anon, authenticated;
revoke all on public.reminders_sent from anon, authenticated;
revoke all on public.note_files from anon, authenticated;

-- The private server key maps to service_role. Grant only the tables used by
-- the local mirror and Trigger.dev backend; browser roles remain revoked.
grant usage on schema public to service_role;
grant select, insert, update, delete on public.cards to service_role;
grant select, insert, update, delete on public.reviews to service_role;
grant select, insert, update, delete on public.reminders_sent to service_role;
grant select, insert, update, delete on public.note_files to service_role;
grant usage, select on all sequences in schema public to service_role;
